export const STOP_WORDS = new Set([
  "a",
  "about",
  "an",
  "and",
  "are",
  "as",
  "at",
  "be",
  "by",
  "can",
  "for",
  "from",
  "how",
  "i",
  "in",
  "is",
  "it",
  "of",
  "on",
  "or",
  "our",
  "should",
  "that",
  "the",
  "their",
  "this",
  "to",
  "what",
  "when",
  "where",
  "which",
  "who",
  "why",
  "with",
  "you",
]);

export const SYNONYMS = {
  ai: ["artificial", "intelligence", "duo"],
  async: ["asynchronous", "remote", "distributed", "documentation", "decision"],
  candidate: ["interview", "hiring", "employee", "onboarding"],
  ci: ["continuous", "integration", "pipeline"],
  cicd: ["ci", "cd", "pipeline", "verify"],
  collaboration: ["communication", "teamwork"],
  comment: ["discussion", "thread", "reply", "mention", "note"],
  comments: ["discussion", "thread", "reply", "mention", "note"],
  culture: ["values", "behaviors"],
  decide: ["decision", "dri", "ownership"],
  decision: ["dri", "ownership", "accountability", "documentation"],
  devsecops: ["development", "security", "operations", "platform"],
  direction: ["strategy", "roadmap", "vision"],
  handbook: ["documentation", "manual", "process", "source", "truth"],
  hire: ["onboarding", "candidate", "employee"],
  issue: ["ticket", "work", "item", "task", "bug"],
  meeting: ["sync", "synchronous", "communication"],
  mr: ["merge", "request"],
  onboarding: ["new", "hire", "ramp", "learning"],
  planning: ["prioritization", "roadmap", "issues", "strategy"],
  prioritize: ["prioritization", "planning", "customer", "value"],
  release: ["ship", "ci", "cd", "pipeline"],
  remote: ["distributed", "asynchronous", "allremote"],
  security: ["secure", "vulnerability", "compliance", "governance", "risk"],
  ship: ["release", "pipeline", "ci", "cd", "verify"],
  ticket: ["issue", "work", "item", "task", "bug", "support"],
  thread: ["discussion", "comment", "reply", "resolve"],
  transparency: ["public", "visible", "documentation"],
  workitem: ["issue", "ticket", "task"],
};

export const TOPIC_RULES = [
  {
    id: "overview",
    label: "GitLab overview",
    pattern: /\b(what is gitlab|who is gitlab|tell me about gitlab|define gitlab|gitlab overview)\b/,
    expansions: ["overview", "company", "devsecops", "platform", "handbook", "direction"],
    boosts: { "gitlab-overview": 0.42, "devsecops-platform": 0.12 },
  },
  {
    id: "async",
    label: "Asynchronous communication",
    pattern: /\b(async|asynchronous|async-first|async work|written update|low[- ]context)\b/,
    expansions: ["asynchronous", "communication", "documentation", "decision", "ownership", "remote", "meeting"],
    boosts: { "async-communication": 0.44, communication: 0.18, meetings: 0.12, "all-remote": 0.08 },
  },
  {
    id: "remote",
    label: "Remote operating model",
    pattern: /\b(remote|distributed|all[- ]remote|time ?zone|timezone|culture)\b/,
    expansions: ["remote", "distributed", "asynchronous", "documentation", "ownership"],
    boosts: { "all-remote": 0.78, "async-communication": 0.1, communication: 0.08 },
  },
  {
    id: "decision",
    label: "Decision-making",
    pattern: /\b(decide|decides|decision|decisions|decision-making|dri|owner|owners|ownership|accountable|accountability)\b/,
    expansions: ["decision", "dri", "ownership", "accountability", "documentation", "async"],
    boosts: { "decision-making": 0.42, communication: 0.12, transparency: 0.1 },
  },
  {
    id: "handbook-first",
    label: "Handbook-first work",
    pattern: /\b(handbook-first|source of truth|single source|document first|documentation-first)\b/,
    expansions: ["handbook", "documentation", "source", "truth", "process", "transparency"],
    boosts: { "handbook-first-work": 0.42, "handbook-home": 0.2, communication: 0.08 },
  },
  {
    id: "onboarding",
    label: "Onboarding",
    pattern: /\b(onboard|onboarding|new hire|new employee|ramp|first week|joining)\b/,
    expansions: ["onboarding", "new", "hire", "employee", "handbook", "learning", "values"],
    boosts: { onboarding: 0.42, "handbook-home": 0.12, values: 0.1 },
  },
  {
    id: "merge-request-reviewers",
    label: "Merge request reviewers",
    pattern:
      /\b(add|assign|request|set|choose|change|remove)\s+(a\s+|the\s+)?reviewers?\b|\breviewers?\b.{0,40}\b(mr|merge request|merge requests)\b|\b(mr|merge request|merge requests)\b.{0,40}\breviewers?\b/,
    expansions: ["merge", "request", "reviewer", "reviewers", "review", "approval", "approvals", "code"],
    boosts: { "merge-request-reviewers": 0.78, "merge-requests": 0.12 },
  },
  {
    id: "comments",
    label: "Comments and discussions",
    pattern:
      /\b(what|where|how|can|could|do|does|add|write|leave|make|create|reply|mention|resolve)\b.{0,45}\b(comment|comments|discussion|discussions|thread|threads|note|notes|reply|mention)\b|\b(comment|comments|discussion|discussions|thread|threads|note|notes|reply|mention)\b.{0,45}\b(gitlab|issue|issues|work item|work items|merge request|merge requests|mr|commit|commits|snippet|snippets)\b|\b(gitlab|issue|issues|work item|work items|merge request|merge requests|mr|commit|commits|snippet|snippets)\b.{0,45}\b(comment|comments|discussion|discussions|thread|threads|note|notes|reply|mention)\b/,
    expansions: ["comment", "discussion", "thread", "reply", "mention", "note", "gitlab", "collaboration"],
    boosts: { "comments-discussions": 0.78, "merge-request-comments": 0.22, "issues-work-items": 0.08 },
  },
  {
    id: "merge-request-comments",
    label: "Merge request comments and threads",
    pattern:
      /\b(comment|comments|discuss|discussion|discussions|thread|threads|reply|replies|mention|mentions|resolve|resolved|suggest|suggestion|suggestions)\b.{0,45}\b(mr|merge request|merge requests)\b|\b(mr|merge request|merge requests)\b.{0,45}\b(comment|comments|discuss|discussion|discussions|thread|threads|reply|replies|mention|mentions|resolve|resolved|suggest|suggestion|suggestions)\b/,
    expansions: ["merge", "request", "comment", "discussion", "thread", "reply", "mention", "resolve", "review"],
    boosts: { "merge-request-comments": 0.82, "merge-requests": 0.12, "merge-request-reviewers": 0.06 },
  },
  {
    id: "merge-request",
    label: "Merge requests and code review",
    pattern:
      /\b(merge request|merge requests|code review|review code|source code|repository|repo)\b|\b(use|create|open|make|raise|merge|review|approve|approval|gitlab|code|request|change|changes|pipeline|branch|comment|discuss|discussion|thread|reply|mention|resolve|suggest)\b.{0,35}\bmr\b|\bmr\b.{0,35}\b(use|create|open|make|raise|merge|review|approve|approval|gitlab|code|request|change|changes|pipeline|branch|comment|discuss|discussion|thread|reply|mention|resolve|suggest)\b/,
    expansions: ["merge", "request", "code", "review", "source", "collaboration", "developer"],
    boosts: { "merge-requests": 0.44, "source-code-stage": 0.16, collaboration: 0.08 },
  },
  {
    id: "ci-cd",
    label: "CI/CD and testing",
    pattern: /\b(ci\/cd|cicd|pipeline|pipelines|testing|tests|automation|verify|release|ship)\b/,
    expansions: ["ci", "cd", "pipeline", "verify", "testing", "automation", "quality", "release"],
    boosts: { "ci-cd": 0.44, "verify-stage": 0.2, "devsecops-platform": 0.08 },
  },
  {
    id: "security",
    label: "Security and governance",
    pattern: /\b(security|secure|vulnerability|vulnerabilities|compliance|governance|risk|remediation)\b/,
    expansions: ["security", "secure", "vulnerability", "governance", "risk", "remediation", "devsecops"],
    boosts: { "security-governance": 0.44, "secure-stage": 0.2, "devsecops-platform": 0.08 },
  },
  {
    id: "planning",
    label: "Planning and prioritization",
    pattern: /\b(planning|prioritize|prioritization|roadmap|issues|portfolio|customer value|tradeoff|tradeoffs)\b/,
    expansions: ["planning", "prioritization", "roadmap", "issues", "strategy", "customer", "value"],
    boosts: { "planning-prioritization": 0.44, "plan-stage": 0.2, "direction-home": 0.1 },
  },
  {
    id: "issues",
    label: "Issues and work items",
    pattern: /\b(ticket|tickets|raise ticket|raise tickets|issue|issues|work item|work items|bug|bugs|task|tasks|support request|feature proposal|issue board|board)\b/,
    expansions: ["issue", "ticket", "work", "item", "task", "bug", "support", "request", "project", "board", "planning"],
    boosts: { "issues-work-items": 0.62, "planning-prioritization": 0.1, "plan-stage": 0.08 },
  },
  {
    id: "values",
    label: "Culture and values",
    pattern: /\b(values|culture|iteration|transparency|transparent|guardrail|guardrails|collaboration|results|efficiency|diversity|inclusion)\b/,
    expansions: ["values", "culture", "transparency", "iteration", "collaboration", "results", "efficiency"],
    boosts: { values: 0.06, transparency: 0.72, iteration: 0.1, collaboration: 0.1 },
  },
  {
    id: "ai",
    label: "AI and GitLab Duo",
    pattern: /\b(ai|artificial intelligence|duo|agent|agents)\b/,
    expansions: ["ai", "duo", "workflow", "devsecops", "security", "product"],
    boosts: { "ai-powered-devsecops": 0.38, "gitlab-duo": 0.32 },
  },
  {
    id: "product",
    label: "Product direction",
    pattern: /\b(direction|strategy|product|devsecops|platform|roadmap|vision)\b/,
    expansions: ["direction", "strategy", "product", "devsecops", "platform", "roadmap"],
    boosts: { "direction-home": 0.26, "devsecops-platform": 0.2 },
  },
];

export const DOMAIN_TERMS = new Set([
  "ai",
  "async",
  "asynchronous",
  "ci",
  "cd",
  "cicd",
  "comment",
  "comments",
  "devsecops",
  "discussion",
  "discussions",
  "duo",
  "gitlab",
  "handbook",
  "issue",
  "issues",
  "mr",
  "pipeline",
  "pipelines",
  "remote",
  "reviewer",
  "reviewers",
  "security",
  "ticket",
  "tickets",
  "thread",
  "threads",
  "values",
]);

export const AMBIGUOUS_KEYWORD_TERMS = new Set([
  "ai",
  "async",
  "ci",
  "cd",
  "cicd",
  "comment",
  "comments",
  "discussion",
  "discussions",
  "duo",
  "issue",
  "issues",
  "mr",
  "pipeline",
  "pipelines",
  "remote",
  "reviewer",
  "reviewers",
  "security",
  "ticket",
  "tickets",
  "thread",
  "threads",
  "values",
]);

export const INTENTS = [
  {
    id: "overview",
    label: "GitLab overview",
    terms: ["gitlab", "overview", "company", "platform", "devsecops"],
  },
  {
    id: "candidate",
    label: "Candidate readiness",
    terms: ["candidate", "interview", "job", "hiring", "employee", "new"],
  },
  {
    id: "culture",
    label: "Culture and values",
    terms: ["culture", "values", "transparency", "iteration", "collaboration", "results"],
  },
  {
    id: "remote",
    label: "Remote operating model",
    terms: ["remote", "async", "asynchronous", "distributed", "meeting", "timezone"],
  },
  {
    id: "product",
    label: "Product direction",
    terms: ["direction", "strategy", "roadmap", "product", "devsecops", "duo", "platform"],
  },
  {
    id: "process",
    label: "Ways of working",
    terms: ["handbook", "process", "documentation", "decision", "communication"],
  },
];
